### ISSUE TITLE
How to build playbook.yml

### ISSUE THREAD

**Issue by 1106944911** [jamonation/haproxy-vip-docker#1]
Hi, I am a new ansible, how to use your haproxy-vip-docker?  can you help me?

**Comment by jamonation** [comment]
Hi @1106944911 , edit `roles/haproxy-vip-docker/vars/main.yml` with definitions for each of the hosts and the subnet where you'd like to run this.

Then run the playbook with a hosts file definition that includes all the systems that you'd like to use.
